### ISSUE TITLE
Journey Pattern with no Journey Pattern Sections

### ISSUE THREAD

**Issue by stev-0** [jclgoodwin/bustimes.org.uk#43]
I found the  journey pattern section **JPS_33-9A-A-y10-2-29-6-H** which doesn't have any information in in timetable https://bustimes.org.uk/services/swe_33-9A-A-y10.xml

It seemed to break my import. I am a few commits back but I couldn't see if / where you had fixed this although your site seems to be working fine. I have a patch that works I think if you haven't fixed it already..

**Comment by jclgoodwin** [comment]
Thanks – I’ve committed a test and some fixes now. Would be interested to see your patch.

The website seemed to be working fine because `swe_33-9A-A-y10-1.xml` is fine, and `swe_33-9A-A-y10-2.xml`’s OperatingPeriod starts on 29 October – https://bustimes.org.uk/services/swe_33-9A-A-y10?date=2017-10-29 was broken.
